- hosts: all
  gather_facts: False
  vars:
    - ansible_connection: ssh
    - ansible_user: root
    - ansible_python_interpreter: /home/root/.bin/python3
    - ansible_ssh_pass: "{{ lookup('env','RM2_PASSWORD') }}"

  tasks:
    - name: Set koreader install-specific vars
      set_fact:
        APPDIR: /home/root/apps
        REPOURL: https://raw.githubusercontent.com/ddvk/remarkable-autoinstall/master/rm2
        RM2FBREPO: https://github.com/ddvk/remarkable2-framebuffer/releases/download/v0.0.2
        KOREADER_BASE: http://build.koreader.rocks/download/nightly/
        KOREADER_VERSION: v2020.12-124-g0c76c73_2021-01-18

    - name: Construct koreader archive filename
      set_fact:
        KOREADER_FILE: 'koreader-remarkable-{{KOREADER_VERSION}}.zip'

    - name: Construct koreader download URL
      set_fact:
        KOREADER_URL: '{{KOREADER_BASE}}{{KOREADER_VERSION}}/{{KOREADER_FILE}}'

    - name: Create app dir
      file:
        path: '{{APPDIR}}/koreader'
        state: directory

    - name: Create script dir
      file:
        path: ~/scripts
        state: directory

    - name: check if touchinjector service exists
      stat:
        path: /etc/systemd/system/touchinjector.service
      register: touchinjector

    - name: Stop touchinjector
      systemd:
        name: touchinjector
        state: stopped
      when: touchinjector.stat.exists == true

    - name: check if koreader already downloaded
      stat:
        path: '/tmp/{{KOREADER_FILE}}'
      register: downloaded

    - name: Download koreader
      get_url:
        url: '{{KOREADER_URL}}'
        dest: '/tmp/{{KOREADER_FILE}}'
      when: downloaded.stat.exists == false

    - name: unzip koreader package
      shell:
        cmd: unzip -o '/tmp/{{KOREADER_FILE}}' -d '{{APPDIR}}'

    - name: Download rm2fb client lib
      command:
        chdir: ~/
        cmd: wget -O librm2fb_client.so.1.0.0 '{{RM2FBREPO}}/librm2fb_client.so.1.0.0'

    - name: Download rm2fb server lib
      command:
        chdir: ~/
        cmd: wget -O librm2fb_server.so.1.0.0 '{{RM2FBREPO}}/librm2fb_server.so.1.0.0'

    - name: Download touchinjector
      command:
        chdir: ~/apps
        cmd: wget -O touchinjector '{{REPOURL}}/apps/touchinjector'

    - name: Make touchinjector executable
      file:
        path: ~/apps/touchinjector
        mode: '0755'

    - name: Download swipeup script
      command:
        chdir: ~/scripts
        cmd: wget -O swipeup.sh '{{REPOURL}}/scripts/swipeup.sh'

    - name: Set swipeup script perms
      file:
        path: ~/scripts/swipeup.sh
        mode: '0755'

    - name: Download ko script
      command:
        chdir: ~/scripts
        cmd: wget -O ko.sh '{{REPOURL}}/scripts/ko.sh'

    - name: Set ko script perms
      file:
        path: ~/scripts/ko.sh
        mode: '0755'

    - name: Setup touchinjector service
      template:
        src: touchinjector.service.j2
        dest: /etc/systemd/system/touchinjector.service

    - name: Start touchinjector
      systemd:
        name: touchinjector
        state: started
        enabled: true
        daemon_reload: yes

    - name: delete koreader downloaded archive
      file:
        path: '/tmp/{{KOREADER_FILE}}'
        state: absent
